version: "3"

services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    restart: on-failure
    ports:
      - 9092:9092
    environment:
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_NUM_PARTITIONS=3
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka-init:
    image: bitnami/kafka:latest
    depends_on:
      - kafka
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    command: >
      bash -c "
        /opt/bitnami/kafka/bin/kafka-topics.sh --create --topic input_topic --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1 &&
        /opt/bitnami/kafka/bin/kafka-topics.sh --create --topic output_topic --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1
      "
    restart: "no"

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    depends_on:
      - kafka
      - zookeeper
    ports:
      - "8080:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=kafka
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181

  equatorial-scraper:
    image: sev3ndie/equatorial-scraper:3.0.0
    container_name: equatorial-scraper
    depends_on:
      - kafka
    environment:
      - KAFKA_CONSUMER_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_CONSUMER_GROUP_ID=equatorial-scraper
      - KAFKA_AUTO_OFFSET_RESET=earliest
      - KAFKA_PRODUCER_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_CONSUMER_TOPIC=input_topic
      - KAFKA_PRODUCER_TOPIC=output_topic
    volumes:
      - $HOME/equatorial-scraper/:/app/files